baseURL: https://merded.zip/
languageCode: en-us
title: Merededdo
theme: PaperMod

params:
  env: production
  disableThemeToggle: true
  HideFooter: true
  socialIcons:
      - name: email
        url: 'mailto:merdedok@gmail.com'
      - name: Telegram
        url: https://t.me/Merededdo
      - name: Signal
        url: 'https://signal.me/#eu/SGAbTaGiEMQXjfR4L-ERxeHlnPRFnMqQumTnNy36Vr4_W1amN55OMZ08CEihn19Y'
      - name: Discord
        url: https://discord.com/users/307774635204804608
      - name: github
        url: https://github.com/Merded
      - name: X
        url: https://x.com/MerdedSpade
  description: "Merededdo"
  profileMode:
    enabled: true
    title: Merededdo
